
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class pop_up extends javax.swing.JFrame {
    Source method = new Source();

    /**
     * Creates new form pop_up
     */
    public pop_up() {
        initComponents();
        setLocationRelativeTo(null);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        stock = new javax.swing.JLabel();
        stockperson = new javax.swing.JComboBox<>();
        stockid = new javax.swing.JTextField();
        stockname = new javax.swing.JTextField();
        stockqty = new javax.swing.JTextField();
        stockdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Stock Identification");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setText("Stock name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel5.setText("Person in Charge");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 120, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, 40));

        stock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stock.setText("Add Stock");
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, 20));

        stockperson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        stockperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockpersonActionPerformed(evt);
            }
        });
        jPanel1.add(stockperson, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, -1));

        stockid.setEditable(false);
        stockid.setBackground(new java.awt.Color(255, 255, 255));
        stockid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(stockid, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 40, 170, 30));

        stockname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(stockname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, 30));

        stockqty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(stockqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, 30));

        stockdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(stockdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    
       if(stockname.getText().isEmpty() || stockqty.getText().isEmpty() || stockdate.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Please fill up all the information");
        }else{
           
            if(stock.getText().equals("Add Stock")){    
        try {
                Statement state = Source.mycon().createStatement();
                state.executeUpdate("insert into tblstock (`stockname`,`quantity`,`date`,`person`) values ('" + stockname.getText() + "','" + stockqty.getText() + "','" + stockdate.getText() + "','" + stockperson.getSelectedItem()+"')");
                method.delete(stockid, stockname, stockqty, stockdate);
                JOptionPane.showMessageDialog(rootPane, "Successfully saved");
                dispose();
            } catch (Exception x) {
                System.out.println(x.getMessage());
            }  
       }  else if(stock.getText().equals("Update Stock")){
                
                 try {
                Statement state = Source.mycon().createStatement();
                state.executeUpdate("update tblstock set  stockname = '" + stockname.getText() + "' , quantity = '" + stockqty.getText() + "', person = '" + stockperson.getSelectedItem() + "' where `id` = '" + stockid.getText() + "'");
                JOptionPane.showMessageDialog(rootPane, "Successfully update!!");
                method.delete(stockid, stockname, stockqty, stockdate);
                dispose();
            } catch (Exception x) {
                System.out.println(x.getMessage());
            }         
       }else if(stock.getText().equals("Delete Stock")){
                try {
                Statement state = Source.mycon().createStatement();
                state.executeUpdate("delete from tblstock where id = '" + stockid.getText() + "'");
                JOptionPane.showMessageDialog(rootPane, "Successfully Deleted!!");
                method.delete(stockid, stockname, stockqty, stockdate);
                dispose();
            } catch (Exception x) {
                System.out.println(x.getMessage());
            }       
       }
       }       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stockpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockpersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockpersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pop_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel stock;
    public javax.swing.JTextField stockdate;
    public javax.swing.JTextField stockid;
    public javax.swing.JTextField stockname;
    public javax.swing.JComboBox<String> stockperson;
    public javax.swing.JTextField stockqty;
    // End of variables declaration//GEN-END:variables
}
